### ISSUE TITLE
Highlight only one row after click

### ISSUE THREAD

**Issue by aswzen** [olifolkerd/tabulator#107]
How to highlight a row after being clicked, i mean only a row, not multiple row..

thank you in advance

**Comment by olifolkerd** [comment]
To do this I would recommend using the ***rowClick*** event callback to toggle a class on that row and use that to highlight the row:

*CSS*
```css
.tabulator .tabulator-row.selected{
	background: #f00 !important; /*highlight selected row red, make sure it overrides existing styling*/
}
```

*JavaScript*
```js
$("#example-table").tabulator({
	columns:[
		{title:"Name", field:"name", sorter:"string", width:150},
		{title:"Age", field:"age", sorter:"number", align:"left"},
		{title:"Height", field:"height", formatter:"star", align:"center", sorter:"number", width:100},
	],
	rowClick:function(e, id, data, row){
		//remove selected class from previously highlighed row
		$("#example-table .tabulator-row.selected").removeClass("selected")
		//add selected class to current row
		row.addClass("selected");
	},
});
```
