### ISSUE TITLE
Show / Hide Table or grey and lock out table via button press

### ISSUE THREAD

**Issue by Landondesi** [olifolkerd/tabulator#1356]
So I have two tables on a page that in the event of a button press I'd like them to show up greyed out and lock them from interaction. Then subsequently, with another button press re-enable them. I can't seem to find in the docs or examples how one would do this?

**Comment by olifolkerd** [comment]
Hey @Landondesi 

The easiest way to do this would be with a bit of css:

```css
.tabulator{
    pointer-event:none;
    -webkit-filter: grayscale(100%);
    -moz-filter: grayscale(100%);
    filter: grayscale(100%);
}
```

The above code will prevent user interaction with the table, thats what the ***pointer-events*** bit does, and then it removes the colour from the table, you could also use ***opacity*** for this instead if you want.

you just want to put those values in a class and then use some JavaScript to toggle that class on the tables.

i hope that helps,

Cheers

Oli :)
