### ISSUE TITLE
change font ?

### ISSUE THREAD

**Issue by shayo** [olifolkerd/tabulator#201]
How do I control the font for the entire table? only for columns?

**Comment by olifolkerd** [comment]
Hey,

You can set the font in css.

Set the font for the entire table:
```css
.tabulator{
    font-family:arial;
}
```

Set the font for a specific column (in this example with a field name of ***age***):
```css
.tabulator .tabulator-cell[data-field="age"]{
    font-family:arial;
}
```

Let me know if that answers your question.

Cheers

Oli
