### ISSUE TITLE
Column header alignment

### ISSUE THREAD

**Issue by WHOI-IS** [olifolkerd/tabulator#241]
Hi.  Great product and very flexible.  I am using column grouping where the group spans several columns.  Is there a way to center the group header text?  You have colVertAlign, do you have colHorizAlign?

thanks

**Comment by olifolkerd** [comment]
Hey,

To do that you can style the ***tabulator-col-title*** class with CSS:

```css
.tabulator .tabulator-col-title{
    text-align:center;
}
```

Cheers

Oli
