### ISSUE TITLE
Set height of header column with configuration

### ISSUE THREAD

**Issue by iursevla** [olifolkerd/tabulator#2951]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to have an option to pass the height of the tabulator column header. This configuration should be global for a Tabulator instance.

**Describe the solution you'd like**
Add configuration option to Tabulator where we define the height of the header column.

Currently I'm doing the following:

Javascript:
```js
  /**
     * Add the height we want to set.
     * @param {string|number} columnHeaderHeight
     */
    setupNormalHeaders(columnHeaderHeight = '45px') {
     // this.element is the Tabulator HTMLElement
      const tabulatorHeaderElement = this.element.getElementsByClassName('tabulator-header')[0];
      tabulatorHeaderElement.style.height = columnHeaderHeight;
      tabulatorHeaderElement.style.minHeight = columnHeaderHeight;
      const tabulatorHeadersElement = tabulatorHeaderElement.getElementsByClassName('tabulator-headers')[0];
      tabulatorHeadersElement.style.height = columnHeaderHeight;
      tabulatorHeadersElement.style.minHeight = columnHeaderHeight;
    }
```

LESS:

```less
.tabulator {
...

    .tabulator-header {
        .tabulator-col {
           ...
           // tabulator is overriding this value with some calculations
           height: 100% !important;
      }
    }
}
```

I'd like to pass an option to Tabulator:

```js
this.tabulator = new Tabulator(this.element, {headerHeight: '45px'}); 
```

**Additional context**
In our current usages of Tabulator we are doing 2 things:
1. Had skewed headers where we override the height using less
2. Any other case, we want to be able to pass an option to set the height from a configuration option.
