### ISSUE TITLE
add option to wrap row's text into newline instead of row's text truncation

### ISSUE THREAD

**Issue by handhikadj** [olifolkerd/tabulator#3267]
**Is your feature request related to a problem? Please describe.**

the row's text is by default truncated and it looks bad

I added:
```css
.tabulator .tabulator-tableHolder .tabulator-table {
  white-space: initial !important;
}

.tabulator-row .tabulator-cell {
  white-space: initial !important;
}
```

to wrap the text into newline

**Describe the solution you'd like**

https://codesandbox.io/s/tabulator-tables-sandbox-forked-5duiu

it would be better if you add:
```js
{
    textWrapping: true
}
```
into the options
