### ISSUE TITLE
word-wrap,  break-word etc, ellipsis behavior for 3.0

### ISSUE THREAD

**Issue by michaelongithub** [olifolkerd/tabulator#333]
Hi Oli
word-wrap/break
I am wondering:
will this be handled for the app programmer in the column headers defs via:

- cssClasses, that have these properties
- cell formatter one has to implement oneself
- future special attributes of column def.

And for cutting off / showing ellipsis: also via cssClasses?

Thanks for info
Cheers, Michael

**Comment by olifolkerd** [comment]
Hi Michael,

I don't really understand what you are asking.

All ellipses are added by the CSS **text-overflow** property which is applied to headers and cells alike when they get to small.

The latest version of the 3.0 beta will be default try and resize columns so that the header text fits in the column.

could you be more specific about the setting you are looking for.

Many Thanks

Oli

**Comment by michaelongithub** [comment]
Hi Oli
If I want / need to control the text wrapping behaviour (white-space, word-wrap) in colums: via cssClass attribute in column definition in 3.0?
Cheers Michael

**Comment by olifolkerd** [comment]
To do that you would need to override the following CSS statements:

```css
/* header */
 #example-table-theme-standard .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title {
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
}

/* cells */
.tabulator .tabulator-tableHolder .tabulator-table .tabulator-row .tabulator-cell {
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis; 
}
```
If we assume you are using the class ***column-wrap*** then you would want something like this:

```css
/* header */
 #example-table-theme-standard .tabulator-header .tabulator-col.column-wrap .tabulator-col-content .tabulator-col-title {
          white-space: normal;
          overflow: hidden;
          text-overflow: clip;
}

/* cells */
.tabulator .tabulator-tableHolder .tabulator-table .tabulator-row .tabulator-cell.column-wrap {
          white-space: normal;
          overflow: hidden;
          text-overflow: clip; 
}
```

Let me know if that helps :)

Cheers

Oli
