### ISSUE TITLE
Animating group toggles + fix alignment + trigger on row click

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3736]
Currently, the triangle icon for the group toggle cannot be animated because the whole row is replaced
Additionally, it would benefit from being rotated in css to avoid positioning issues
Also, currently, if you click on the row, it doesn't trigger the open/close of the group

Here is some css that does just that: no need to adjust margin-right because of this and overall, the icon is better positioned

```css

.tabulator-row.tabulator-group .tabulator-arrow {
    display: inline-block;
    width: 0;
    height: 0;
    margin-right: 16px;
    border-top: 6px solid transparent;
    border-bottom: 6px solid transparent;
    border-right: 0;
    border-left: 6px solid #666;
    vertical-align: middle;
    animation: transform ease-in-out 0.2s; /* Doesn't work because node is replaced */
}

.tabulator-row.tabulator-group.tabulator-group-visible .tabulator-arrow {
    transform: rotate(90deg);
    margin-right: 16px;
    border-top: 6px solid transparent;
    border-bottom: 6px solid transparent;
    border-right: 0;
    border-left: 6px solid #666;
}
```

Easy wins: 
- rotate the icon instead of adjust the border properties
- maybe trigger the open/close on row click. this can be done by listening to click on the header, but that could be backed in

Harder:
- do not replace the header row to allow animation of the rotation

Alternative option:
I've used css animations. While they do work great, they also trigger on first paint which is not ideal. Maybe there should be a class added if the row group has been replaced due to open/close action. This would allow use css animations

**Comment by lekoala** [comment]
Additionnaly, the row group could be **vertically** centered

```css
.tabulator-group {
    display: flex;
    align-items: center;
}
```
