### ISSUE TITLE
Default alert UI work better with a dark ui

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3738]
The default alert ui has a dark background that works well in a dark background (like in tabulator website) but is not ideal on a light setting (eg: bootstrap light theme)

There should be a way to distinguish light/dark themes. This is easily fixed with one line of css, nevertheless it's probably going to affect everyone with a light background

```css
.tabulator .tabulator-alert {
    background: rgba(255, 255, 255, 0.6);
}
```
