### ISSUE TITLE
usage of css variables

### ISSUE THREAD

**Issue by lekoala** [olifolkerd/tabulator#3764]
**Is your feature request related to a problem? Please describe.**
I've been tweaking the css theme for a while, and while you can obviously compile everything yourself, i think it would be easier if there was some top level css variables provided to easily theme colors to your liking without the need to compile anything.

**Describe the solution you'd like**
For example, it would allow things like this in a bootstrap 5 context

```css
.tabulator {
    --tabulator-primary-color: var(--bs-link-color, #0071c4);
    --tabulator-primary-hover-color: var(--bs-link-hover-color, #0062ab);
}
.tabulator .tabulator-footer .tabulator-page.active {
    background-color: var(--tabulator-primary-color);
    border-color: var(--tabulator-primary-color);
}
```

the fact that you can nest css variables and provide fallback values make sure you always get at least one value. The fallback color could still be generated from scss variables.

I expected this to be more useful once bootstrap 5.2 is released as they will use much more of this approach
https://getbootstrap.com/docs/5.2/customize/css-variables/

**Describe alternatives you've considered**
Compiling from scss, but that means I could miss future updates or fixes.
I'm also sometimes working with more dynamic themes where its much easier to set a couple of global css vars rather than having to compile the whole thing each time (eg: for skins on website where color is user configurable)
