### ISSUE TITLE
Wrap header -- documentation for 3.1

### ISSUE THREAD

**Issue by MikhailKlemin** [olifolkerd/tabulator#407]
Hello!
The header is still not wraps as per

> Wrap Column Header Title Text
> By default Tabulator will try and keep column header titles on one line, truncating the text with ellipsis if it gets wider that the column.
> If you would like to wrap the text instead then you will need to edit the CSS white-space value for the column headers and set it to normal.
> 

```
.tabulator .tabulator-header .tabulator-col,
.tabulator .tabulator-header .tabulator-col-row-handle {
    white-space: normal;
}
```

Using latest `tabulator.min.css`

**Comment by olifolkerd** [comment]
Apologies, it looks like there is an issue with the documentation there.

It should be:
```css
.tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title{
    white-space: normal;
}
```

I will update the documentation now

Thanks for letting me know.

Oli
