### ISSUE TITLE
Column filter like handsontable

### ISSUE THREAD

**Issue by andreaordonselli** [olifolkerd/tabulator#4225]
This is the column filter of handsontable.
Is there something similar for tabulator?
Documentation here: https://handsontable.com/docs/javascript-data-grid/column-filter/
Many thanks for your work.

![image](https://github.com/olifolkerd/tabulator/assets/89784373/7a63b5dc-fe3a-4197-b143-835eefd1f49b)

**Comment by andreaordonselli** [comment]
Here is the code that adds the operator filter.
I leave a short video.

![filter operator](https://github.com/olifolkerd/tabulator/assets/89784373/31fbf54a-5b3b-4174-8771-2953ae3ace05)


**html**
```html
    <div class="menu-overlay">
      <div class="filter-operator-window">
        <button class="filter-operator-close-button">x</button>
        <h3>Filtra per operatore </h3>
        <select id="filter-operator-select">
          <option value="=" selected>filtra numero: = uguale</option>
          <option value="!=">filtra numero: != diverso</option>
          <option value="<">filtra numero: &lt; minore</option>
          <option value="<=">filtra numero: &lt;= minore-uguale</option>
          <option value=">">filtra numero: &gt; maggiore</option>
          <option value=">=">filtra numero: &gt;= maggiore-uguale</option>
          <option value="between">filtra numero: da/a</option>
          <option value="contains">filtra testo: contiene</option>
          <option value="starts_with">filtra testo: inizia con</option>
          <option value="ends_with">filtra testo: finisce con</option>
        </select>
        <input type="text" id="filter-value-1" placeholder="Inserisci il valore da filtrare"></input>
        <input type="text" id="filter-value-2" placeholder="Inserisci il valore da filtrare"></input>
        <button id="apply-filter-button">Salva</button>
      </div>

      <div class="filter-menu">
        <button class="close-menu-button">x</button>
        <button id="filter-operator">Filtra per operatore...</button>
        <div id="filter-status">
          <span class="filter-text"></span>
          <button id="delete-filter-operator">x</button>
        </div>

        <input type="text" id="filter-input" placeholder="Cerca..."></input>
        <button id="clear-selection-button"></button>
        <button id="select-all-button"></button>
        <div id="value-select">
        </div>
        <button id="remove-filter-button"></button>
        <button id="filter-button">OK</button>
        <div class="filter-menu-overlay">
        </div>
      </div>
    </div>
```
**css**
```css
#filter-operator {
  background: unset;
}
#filter-operator:hover {
  background-color: #ddd;
}
.filter-operator-window {
  position: absolute;
  bottom: 180px;
  left: -25px;
  width: 250px;
  height: auto;
  background-color: #fff;
  border: 1px solid #ccc;
  padding: 10px;
  z-index: 1;
  display: none;
}

.filter-operator-close-button {
  position: relative;
  float: right;
  margin-top: unset !important;
  border: 1px solid black;
  border-radius: 4px;
  cursor: pointer;
}
.filter-operator-close-button:hover {
  background-color: #ddd;
}

.filter-operator-window h3 {
  margin: 0 0 10px 0;
}

.filter-operator-window select,
.filter-operator-window input {
  width: 100%;
  margin-top: 4px;
}

.filter-operator-window button {
  margin-top: 10px;
}

#filter-value-2 {
  display: none;
}

#apply-filter-button {
  border: 1px solid black;
  border-radius: 4px;
  cursor: pointer;
  float: right;
  background-color: #4caf50 !important;
  color: white;
}

#apply-filter-button:hover {
  background-color: #ddd;
}

#filter-status {
  position: relative;
  display: none;
}

#filter-status .filter-text {
  display: inline-block;
}

#delete-filter-operator {
  background-color: unset;
  color: red;
  border: none;
  cursor: pointer;
  display: none;
  bottom: 1px;
  position: relative;
}
```
**javascript**
```javascript
// When you click the "Filter operator" button, the window pops up
        $('#filter-operator').off('click').on('click', function() {
          $('.filter-operator-window').show().addClass('active');
          $('#filter-operator-select').val('=');
          $('#filter-value-1').val('');
          $('#filter-value-2').val('');
        });
      
        // When you click the "Filter operator close button" the window is closed
        $('.filter-operator-close-button').off('click').on('click', function() {
          $('.filter-operator-window').hide().removeClass('active');
        });

        function filterOperator() {
          // Get the operator and values ​​from the drop-down menu and input boxes
          var operator = $('#filter-operator-select').val();
          var value1 = $('#filter-value-1').val();
          var value2 = $('#filter-value-2').val();

          // Update dynamic lettering with active filter
          var filterText = 'Filtro:  ' + operator + '  ' + value1 + '  ' + value2;
          $('#filter-status .filter-text').text(filterText);
          $('#filter-status').show();
          $('#delete-filter-operator').show();

          // Filter the options contained in the #value-select input
          $('#value-select input').each(function() {
              var $label = $(this).closest('label');
              // Check if the label has display: none
              if ($label.css('display') === 'none') {
                return; // Ignore value with display: none
              }

              var elementValue = $(this).val().toLowerCase();

              // If the option matches the filter, show it
              switch (operator) {
                case '=':
                  if (elementValue === value1) {
                    $label.show();
                  } else {
                    $label.hide();
                  }
                  break;
                case '!=':
                  if (elementValue !== value1) {
                    $label.show();
                  } else {
                    $label.hide();
                  }
                  break;
                case '<':
                  if (parseInt($(this).val()) < parseInt(value1)) {
                    $label.show();
                  } else {
                    $label.hide();
                  }
                  break;
                case '<=':
                  if (parseInt($(this).val()) <= parseInt(value1)) {
                    $label.show();
                  } else {
                    $label.hide();
                  }
                  break;
                case '>':
                  if (parseInt($(this).val()) > parseInt(value1)) {
                    $label.show();
                  } else {
                    $label.hide();
                  }
                  break;
                case '>=':
                  if (parseInt($(this).val()) >= parseInt(value1)) {
                    $label.show();
                  } else {
                    $label.hide();
                  }
                  break;
                case 'between':
                  var val = parseInt($(this).val());
                  if (val >= parseInt(value1) && val <= parseInt(value2)) {
                    $label.show();
                  } else {
                    $label.hide();
                  }
                  break;
                case 'contains':
                  if (elementValue.includes(value1)) {
                    $label.show();
                  } else {
                    $label.hide();
                  }
                  break;
                case 'starts_with':
                  if (elementValue.startsWith(value1)) {
                    $label.show();
                  } else {
                    $label.hide();
                  }
                  break;
                case 'ends_with':
                  if (elementValue.endsWith(value1)) {
                    $label.show();
                  } else {
                    $label.hide();
                  }
                  break;
                default:
                  // Nothing needs to be done if the operator is invalid
                  break;
              }
            });
        }

        // When you click the "OK" button, the filter is applied to the options contained in the value-select
        $('#apply-filter-button').off('click').on('click', function() {

          filterOperator(); // Adding the call to the filterOperator() function

          // Hide the window
          $('.filter-operator-window').hide().removeClass('active');
        });

        // When the option in the dropdown menu is changed
        $('#filter-operator-select').off('click').on('change', function() {
          var selectedOperator = $(this).val();

          // Show input #filter-value-2 only if the selected operator is "between"
          if (selectedOperator === 'between') {
            $('#filter-value-2').show();
          } else {
            $('#filter-value-2').hide();
          }
        });   

        // When you click the "x" button to delete the filter
        $('#delete-filter-operator').off('click').on('click', function() {
          // Get the current value into the input of the #filter-input
          var filterInputValue = $('#filter-input').val().toLowerCase();

          // Show all hidden values
          $('#value-select input').closest('label').show();

          // Hide the filter text and the "x" button
          $('#filter-status').hide();
          $('#delete-filter-operator').hide();

          // Reset the operator and values ​​to their default values
          $('#filter-operator-select').val('=');
          $('#filter-value-1').val('');
          $('#filter-value-2').val('');

          // Reapply the input filter if there is an inserted value
          if (filterInputValue !== '') {
            filterListValues(filterInputValue);
          }
        });

        // Function to filter the input values ​​based on the value entered in the input-box
        function filterListValues(query) {
          $('#value-select input[type="checkbox"]').each(function(i, elem) {
            var $label = $(this).closest('label');
            if (elem.value.toLowerCase().indexOf(query) !== -1) {
              $label.show();
            } else {
              $label.hide();
            }
          });
        }

        // When the value in the input-box is changed
        $('#filter-input').off('keyup').on('keyup', function() {
          var query = this.value.toLowerCase();
          filterListValues(query);

          // Get the values ​​of #filter-value-1 and #filter-value-2
          var value1 = $('#filter-value-1').val();
          var value2 = $('#filter-value-2').val();

          // Apply filterOperator() only if at least one of the two values ​​has been set
          if (value1 !== '' || value2 !== '') {
            filterOperator();
          }
        });
```
