### ISSUE TITLE
Missing Light Theme on tabulator.info

### ISSUE THREAD

**Issue by Nemecsek** [olifolkerd/tabulator#4553]
Please **add Light Theme to tabulator.info**: at least for me it is quite difficult to read the code and the text.
I didn't find the theme switch, if any.

Thank you!

**Comment by Nemecsek** [comment]
@ERTVZ you are right!
 
I didn't try with different browser: The original screenshot comes from **Firefox 128.0 in Ubuntu 20.04**. In Chrome 124.0, Edge 127.0, Brave 1.16 the table is like yours and perfectly readable...

The problem comes from `font-weight`. In `app.css` we have
```css
body {
  font-family: 'Open Sans', sans-serif;
  font-size: 14px;
  font-weight: lighter;
  background: #202020;
  color: #ccc;
  height: 100%;
}
``` 
`font-weight` is assigned 100, that is rendered ultra-thin in Firefox.

Here the difference between different `font-weight` in Firefox:
|  100 | 200  | 300  | 400  |
|--|--|--|--|
|![Screenshot_20240814_105540_100](https://github.com/user-attachments/assets/6e0c4b80-bd6f-4877-8b9c-2bc8bc6cba60)|![Screenshot_20240814_105606_200](https://github.com/user-attachments/assets/12b770e2-85e9-4f2e-9dee-8b8000008e67)|![Screenshot_20240814_105628_300](https://github.com/user-attachments/assets/9c800527-0610-41f4-a743-26af13eddc1e)|![Screenshot_20240814_105646_400](https://github.com/user-attachments/assets/ad1784ed-2021-48d6-b37b-0f6b6c9c6476)|
