### ISSUE TITLE
i cant find the onmouseover function in the tabulator.js .

### ISSUE THREAD

**Issue by diffcultpro** [olifolkerd/tabulator#665]
As the title ,i want to change the row background-color when  i move the cursor on that row .but i cant find 
the onmouseover function, or is there a another way to solve this issue ?

**Comment by olifolkerd** [comment]
if you just want the background colour of all rows to change when the mouse is over them you can use the CSS ***:hover*** selector:

```css
.tabulator .tabulator-row:hover{
    background-color:red;
}
```

if you wanted to specifically access the ***mouseover*** event then you could bind to this in the ***rowFormatter***:
```js
$("#example-table").tabulator({
    rowFormatter:function(row){
        //row - row component

        row.getElement().on("mouseover", function(){
            //do something
        });
    },
});
```

Let me know if that helps

Cheers

Oli

**Comment by diffcultpro** [comment]
Also,i have another problem is ,how to change the header's background-color ?
i do it like this,but it doesn't work ,thank you . 
$(".tabulator .tabulator-header, .tabulator .tabulator-header .tabulator-col").css("background-color","#00578C");

**Comment by olifolkerd** [comment]
I would recommend you do this in CSS, all elements in tabulator are generated programatically so trying to access them outside of Tabulator can lead to any changes being overwritten:

```css
.tabulator .tabulator-header .tabulator-col{
    background-color:#00578C;
}
```

Ensure the css is included after the tabulator css file so it takes precedence.

Cheers

Oli

**Comment by diffcultpro** [comment]
so you mean that . if  i want  change the css anywhere i just need do in css , not need to change the tabulator.js right ?

**Comment by olifolkerd** [comment]
that would be ideal yes.

If you want to change it on a row by row or cell by cell basis then you can use the ***rowFormatter*** or cell formatters to do that.

Cheers

Oli

**Comment by diffcultpro** [comment]
ok，thanks

**Comment by rpmade** [comment]
How about just changing one specific column header?

**Comment by olifolkerd** [comment]
each column header has a ***tabulator-field*** attribulte that is set to the field of that column:

```css
.tabulator .tabulator-header .tabulator-col[tabulator-field="age"]{
    background-color:#00578C;
}
```

I hope that helps.

Cheers

Oli :)
