### ISSUE TITLE
Show on Hover

### ISSUE THREAD

**Issue by vipera7** [olifolkerd/tabulator#911]
Hey Oli!

Is it possible to show a colum content when I hover a row ? 

Something like this :

![alt text](http://www.image-heberg.fr/files/1519297543604287285.png "Logo Title Text 1")

I tried this css style but the result is not what I'm expecting.

```css
.tabulator .tabulator-row .tabulator-cell[tabulator-field="action"]:hover{
    display:block !important;
}
.tabulator .tabulator-row .tabulator-cell[tabulator-field="action"]{
    display:none !important;
}
```

Cheers
