### ISSUE TITLE
Can tabulator have custom table titles? 

### ISSUE THREAD

**Issue by davidawad** [olifolkerd/tabulator#988]
Take a look at the following screenshot: 

<img width="905" alt="screen shot 2018-03-22 at 11 42 03 am" src="https://user-images.githubusercontent.com/4019054/37780929-22c7f862-2dc6-11e8-9e89-63a1bfdd759e.png">

the column header "Date of Birth" is cut off. Is it possible to retain the same width if you were able to use a custom title? 

For example if title could even just be set to "Date\nOf\nBirth" then you could have a smaller width while still communicating the intent of the column.

**Comment by olifolkerd** [comment]
Hey @davidawad,

If you are using the ***fitColumns*** layout mode then the columns will only take up the available space to fill the table which can result in some columns being trucated.

If you would prefer that the column headers wrapped instead of being truncated then a bit of CSS is all you need to do that:

```css

.tabulator .tabulator-header .tabulator-col .tabulator-col-content .tabulator-col-title{
	white-space: normal;
	text-overflow: clip;
}
```

Include that anywhere after your tabulator stylesheet and you should be good.

Let me know how you get on.

Cheers

Oli :)
